trigger: 
  branches:
    include:
      - feature
  paths:
    include:
      - infra/statefileBackend/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: 'latest'
  
stages:
  - stage: Checkout
    displayName: 'Checkout Code'
    jobs:
      - job: Checkout
        displayName: 'Checkout Code'
        steps:
          - checkout: self
            clean: true

  - stage: Terraform
    displayName: 'Terraform Operations' 
    dependsOn: Checkout
    jobs:
      - job: Terraform
        displayName: 'Terraform Operations'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)


  - stage: AzureLogin
    displayName: 'Azure Login using OIDC'
    dependsOn: Terraform
    jobs:
      - job: AzureLogin
        displayName: 'Azure Login using OIDC'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureServiceConnectionApatil'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                    export ARM_USE_OIDC=true
                    export ARM_CLIENT_ID=$servicePrincipalId
                    export ARM_TENANT_ID=$tenantId
                    export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                    
                    echo "Logged in Successfully"
