trigger: 
  branches:
    include:
      - feature
  paths:
    include:
      - infra/statefileBackend/**

pool:
  name: apatil-pool

stages:
  - stage: Validate
    displayName: Validate code
    jobs:
      - job: Init
        displayName: Init Terraform
        steps:
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/statefileBackend/'
            backendServiceArm: 'Azure subscription 1(05ff4ddb-aff1-402d-98e9-fb103401eee6)'
            backendAzureRmStorageAccountName: 'aptfstorageaccount'
            backendAzureRmContainerName: 'featuretf'
            backendAzureRmKey: 'featuretf'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/statefileBackend/'

  - stage: Scan
    dependsOn: Validate
    displayName: Scan using Tfsec
    jobs: 
      - job: Scan
        displayName: Scan using Tfsec
        steps:
           - script: |
              tfsec . --format sarif --out tfsec-results.sarif --soft-fail
             displayName: 'Run tfsec Security Scan'

  - stage: Scan_Tflint
    dependsOn: Validate
    displayName: Scan using TFlint
    jobs:
      - job: Scan_Tflint
        steps:
          - script: |
              tflint --init
              tflint --format sarif > tflint-results.sarif || true
            displayName: 'Run TFLint Scan'
          
  - stage: Plan
    displayName: Terraform Plan
    jobs:
      - job: Plan
        displayName: Terraform Plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/statefileBackend/'
              environmentServiceNameAzureRM: 'Azure subscription 1(05ff4ddb-aff1-402d-98e9-fb103401eee6)'
